import os
os.system("apt-get update")
os.system("pip install socket")
os.system("pip install pyinstaller")
os.system("pip install subprocess")
os.system("pip install simlejson")
os.system("pip install base64")
os.system("pip install pyautogui")
os.system("pip install pyttsx3")
os.system("pip install sys")
os.system("pip install shutil")
os.system("pip install termcolor")
os.system("pip install colorama")
os.system("pip3 install socket")
os.system("pip3 install subprocess")
os.system("pip3 install simlejson")
os.system("pip3 install base64")
os.system("pip3 install pyautogui")
os.system("pip3 install pyttsx3")
os.system("pip3 install sys")
os.system("pip3 install shutil")
os.system("pip3 install termcolor")
os.system("pip3 install colorama")
os.system("pip3 install pyinstaller")
